<template>
  <div class="calendar" :class="{active: _show}">
    <div class="title">
      <span>{{ targDate.year() || 1970 }}年{{targDate.month() || 1}}月</span>
      <div class="wrap">
        <a href="javascript:void(0);" @click="prevMonth">&lt;</a>
        <a href="javascript:void(0)" @click="goToday">今天</a>
        <a href="javascript:void(0);" @click="nextMonth">&gt;</a>
      </div>
      <div class="wrap">
        <icon name="reset" @click.native="reset"/>
        <icon name="clear" @click.native="hidePanel"/>
      </div>
    </div>
    <ul class="weekdays">
      <li v-for="(weekday, i) in weekdays" :key="i">{{weekday}}</li>
    </ul>
    <div class="wrap">
      <ul class="days">
        <li
          v-for="(day, index) in dayArr"
          :key="index"
          :class="{'today': day.isToday, 'cur-month': day.isTarMonth, 'selected': day.isSelected}"
          @click="selectDate(day, index)"
        >
          <span>{{day.date.day()}}</span>
        </li>
      </ul>
    </div>
  </div>
</template>

<script>
import Date2 from '../../class/Date2'
import Icon from './Icon'

export default {
  name: 'calendar',
  props: {
    show: {
      type: Boolean
    },
    value: {
      validator: function (value) {
        return value instanceof Date || value === null
      }
    }
  },
  components: {
    icon: Icon
  },
  data () {
    return {
      // current: null,  // current Date <Date2>
      weekdays: { 0: '周日', 1: '周一', 2: '周二', 3: '周三', 4: '周四', 5: '周五', 6: '周六' },
      monthOffset: 0,  // offset against _value
      targDate: null, // <Date2>
      dayArr: [] // generated by targDate<Date2>
    }
  },
  computed: {
    _show: {
      get () {
        // initialize targDate & monthOffset when toggling Calendar
        if (this.show) {
          this.targDate = this._value ? new Date2(this._value) : new Date2()
          this.monthOffset = 0
        } else {
          this.targDate = new Date2()
        }
        return this.show
      },
      set (val) {
        // refresh targDate when this component shown
        this.$emit('update:show', val)
      }
    },
    _value: {
      // the chosen Date
      get () {
        return this.value
      },
      set (val) {
        this.$emit('input', val)
      }
    }
  },
  watch: {
    targDate: function (val) {
      this.dayArr = this._generateMonthArr(val, this.monthOffset)
    }
  },
  created: function () {
    if (!this.targDate) {
      this.targDate = new Date2()
    }
  },
  methods: {
    selectDate: function (day) {
      this._value = day.date.date
      this.hidePanel() // targDate & monthOffset will change
    },
    reset: function () {
      this._value = null
      this.targDate = new Date2()
      this.monthOffset = 0
    },
    goToday: function () {
      this.monthOffset = 0
      this.targDate = new Date2()
    },
    prevMonth: function () {
      this.monthOffset--
      this.targDate = this.targDate.previousMonth
    },
    nextMonth: function () {
      this.monthOffset++
      this.targDate = this.targDate.nextMonth
    },
    hidePanel: function () {
      this._show = false
    },
    showPanel: function () {
      this._show = true
    },
    _generateMonthArr (targetDate, monthOffset) {
      // generate an array of current month according to targetDate<Date2>
      if (targetDate instanceof Date) {
        targetDate = new Date2(targetDate)
      } else if (!(targetDate instanceof Date2)) {
        return []
      }
      let startPadding = targetDate.monthBeginning.weekday() || 0
      let endPadding = 6 - targetDate.monthEnding.weekday() || 0
      let dayCount = targetDate.monthEnding.day() || 0
      let startPaddingArr = Array(startPadding).fill(0).map((_, i) => {
        return {
          date: targetDate.day(i + 1 - startPadding),
          isToday: false,
          isSelected: false,
          isTarMonth: false
        }
      })
      let endPaddingArr = Array(endPadding).fill(0).map((_, i) => {
        return {
          date: targetDate.day(dayCount + i + 1),
          isToday: false,
          isSelected: false,
          isTarMonth: false
        }
      })
      let tarMonthArr = Array(dayCount).fill(0).map((_, i) => {
        return {
          date: targetDate.day(i + 1),
          isToday: false,
          isSelected: false,
          isTarMonth: true
        }
      })
      if (monthOffset === 0) {
        tarMonthArr[targetDate.day() - 1].isSelected = true
      }
      if (tarMonthArr[0].date.month() === new Date2().month()) {
        tarMonthArr[new Date2().day() - 1].isToday = true
      }
      return [...startPaddingArr, ...tarMonthArr, ...endPaddingArr]
    }
  }
}
</script>
<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
.calendar {
  width: 400px;
  border: 1px solid green;
  display: none;
  &.active {
    display: block;
  }
  .title {
    width: 100%;
    background: #379392;
    color: #f2f2f2;
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
    padding: 0.5rem 0.5rem;
    > span {
      font-size: 1.25rem;
      text-align: left;
    }
    > .wrap {
      > a {
        color: #fff;
        opacity: 0.8;
        padding: 0 0.25rem;
        &:hover {
          opacity: 1;
        }
      }
      > .icon {
        width: 1rem;
        height: 1rem;
        margin-left: 0.125rem;
        margin-bottom: -0.125rem;
        fill: #cdcdcd;
        &:hover {
          cursor: pointer;
          fill: #fff;
        }
      }
    }
  }
  > .weekdays {
    width: 100%;
    display: flex;
    flex-wrap: nowrap;
    justify-content: space-around;
    background: #e3e5e9;
  }
  > .wrap {
    width: 100%;
    position: relative;
    &::before {
      content: "";
      display: inline-block;
      width: 0.1px;
      height: 0;
      padding-bottom: 75%;
    }
    .days {
      width: 100%;
      height: 100%;
      display: flex;
      flex-wrap: wrap;
      position: absolute;
      left: 0;
      top: 0;
      li {
        width: 14.28%;
        margin: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        background: #d1d1d1;
        border-top: 1px solid #d1d1d1;
        border-left: 1px solid #d1d1d1;
        > span {
          display: inline-block;
          width: 1.75rem;
          height: 1.75rem;
          border-radius: 50%;
          line-height: 1.75rem;
          color: #999;
        }
        &:hover {
          cursor: not-allowed;
        }
        &.cur-month {
          cursor: pointer;
          background: #f1f1f1;
          border-top: 1px solid #ccc;
          border-left: 1px solid #ccc;
          > span {
            color: #285943;
          }
          &:nth-child(7n + 1) {
            border-left: none;
          }
          &.today {
            > span {
              background: #379392;
              color: #fff;
            }
          }
          &.selected {
            background: #f4f5f9;
            > span {
              line-height: 1.5rem;
              border: 0.125rem solid #379392;
            }
            &:hover {
              background: #f1f1f1;
            }
          }
          &:hover {
            background: #d8e6e7;
          }
          &:active {
            background: #f4f5f9;
            > span {
              line-height: 1.5rem;
              border: 0.125rem solid #379392;
            }
          }
        }
      }
    }
  }
}
</style>
